"""     Relational/Comparision Operators   """

a=int(input("Enter the Value of a:"))
b=int(input("Enter the Value of b:"))
print(f"The value of {a} < {b} is {a<b}")
print(f"The value of {a} > {b} is {a>b}")
print(f"The value of {a} <= {b} is {a<=b}")
print(f"The value of {a} >= {b} is {a>=b}")
print(f"The value of {a} == {b} is {a==b}")
print(f"The value of {a} != {b} is {a!=b}")

a=int(input("Enter the Value of a:"))
b=int(input("Enter the Value of b:"))
print("The value of %d<%d=%d"%(a,b,a<b))
print("The value of a=%d , b=%d and a<b=%d"%(a,b,a<b))
print("The value of a=%d , b=%d and a>b=%d"%(a,b,a>b))
print("The value of a=%d , b=%d and a<=b=%d"%(a,b,a<=b))
print("The value of a=%d , b=%d and a>=b=%d"%(a,b,a>=b))
print("The value of a=%d , b=%d and a==b=%d"%(a,b,a==b))
print("The value of a=%d , b=%d and a!=b=%d"%(a,b,a!=b))
